export const LOCAIS = [
  'Bridge',
  'ScreenBridge',
  'HelmBridge',
  'BackPanelBridge',
  'SecurityBridge',
  'ReadyRoom',
  'ConferenceRoom',
  'NotListedRoom',
  'Engineering',
  'TenForward',
  'Corridor',
  'Elevator',
  'Sickbay',
  'HolodeckEntrance',
  'TransporterRoom',
  'ShuttleBay',
  'ShuttleCraft',
  'ObservationLounge',
  'CaptainsQuarters',
  'CargoBay',
  'JeffriesTube',

  'InsideKlingonShip',
  'InsideBorgShip',
  'InsideRomulanShip',
  'InsideFederationShip',
  
  'SpaceDeep',
  'SpaceStation',
  'SpaceOrbitPlanet',
  'SpaceOrbitStar',
  'PlanetSurface',
];

export const CHARACTERS = [
  'none',
  'Picard',
  'Data',
  'Ricker',
  'Geordi',
  'Worf',
  'Troi',
  'DraCrusher',
  'Wesley',
  'Q',
  'Guinan',
  'Almirante',
  'Klingon',
  'Borg',
  'Romulan',
  
  'Crowd',

  'EnterpriseFront',
  'EnterpriseBack',
  'EnterpriseSide',
  
  'KlingonShip',
  'BorgShip',
  'RomulanShip',  
  'FederationShip',

];

export const CHARACTERS_ACTIONS = {
  light: [
    'dark',
    'bright',
    'flashing',
    'emergency'
  ],
  camera: [
    'closeUp',
    'far',
    'side',
    'top',
    'bottom',
    'back',
    'front',
    'shaking'
  ],
  'looking-at': [
    'bridgeScreen',
    'bridgeSecurityPanel',
    'bridgeBackPanel',
    'bridgeHelm',
    'bridgeCaptainChair',
    'monitor',
    'window',
    'Picard',
    'Data',
    'Ricker',
    'Geordi',
    'Worf',
    'Troi',
    'DraCrusher'
  ],
  'talking/sound': [
    'silence',
    'talking',
    'warning',
    'shouting',
    'crying',
    'laughing',
    'surprised',
    'singing',
    'playingInstrument',
    'trainnig',
  ],
  movement: [
    'seated',
    'lying',
    'standing',
    'walking',
    'running',
    'dancing',
    'shaking',
    'flying',
    'warp',
  ],
  fighting: [
    'fists',
    'phasers',
    'photonTorpedos',
    'disruptors',
    'sword',
    'bat\'leth'
  ],
};
